site_name: Règles du Loup Garou Pour Une Nuit
site_url: https://log1k-png.github.io/LGPUN_rules/
use_directory_urls: true
theme:
  name: material
  palette:
    scheme: slate
nav:
  - Français: index.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  # - attr_list
  # - md_in_html
  # - pymdownx.blocks.caption
