site_name: Règles du Loup Garou Pour Une Nuit
site_url: https://log1k-png.github.io/LGPUN_rules/
use_directory_urls: true
theme:
  name: slate
nav:
  - Home: index.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
